[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install --production=false']

[phases.build]
cmds = ['npm run build', 'cd backend && npm install --production']

[start]
cmd = 'NODE_ENV=production node backend/server.js'
